language: php
before_script: 
  - composer self-update
  - composer install
php:
  - 5.5
  - 5.6
  - 7.0
script:
  - phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
  - email: true
matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true
