language: php
before_script: 
  - composer self-update
  - composer install
php:
  - 7.0
  - 7.1
script:
  - phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
  irc:
    channels:
      - "irc.phpfreaks.com#help"
    on_success: always
    on_failure: always
matrix:
  fast_finish: true
