version: 2.1
orbs:
  php: circleci/php@1
jobs:
  test-php:
    docker:
      - image: cimg/php:8.4.4
    steps:
      - checkout
      - php/install-packages
      - run:
          name: run tests
          command: |
            ./vendor/bin/phpunit --coverage-glover=coverage.clover
            wget https://scrutinizer-ci.com/ocular.phar
            php ocular.phar code-coverage:upload --format=php-clover coverage.clover
      - store_artifacts:
          path: /tmp/artifacts
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: "#e.g. ./deploy.sh"
workflows:
  build-and-test:
    jobs:
      - test-php:
          context: []
