version: 2.1
orbs:
  php: circleci/php@1
  evals: circleci/evals@2.0
jobs:
  test-php:
    docker:
      - image: cimg/php:8.2.7-node
    steps:
      - checkout
      - php/install-packages
      - run:
          name: run tests
          command: ./vendor/bin/phpunit
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: "#e.g. ./deploy.sh"
  evals-test-assertions-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - evals/test:
          assertions: assertions.json
          metrics: eval_results.json
          results: test_results.xml
workflows:
  build-and-test:
    jobs:
      - test-php:
          context: []
  test-eval-workflow:
    jobs:
      - evals-test-assertions-job
